default: &default
  # Primary database like as Main database
  # adapter: sqlite3
  adapter: postgresql
  timeout: 60000
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default