source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
ruby '3.1.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.4'
# Use sqlite3 as the database for Active Record
#gem 'sqlite3', '~> 1.4'

# gem 'sqlite3', '~> 1.4'
gem 'pg', '~> 1.2.3'
gem 'puma', '~> 5.0'
gem 'bcrypt', '~> 3.1.7'
gem 'rack-cors'
gem 'redis', '~> 4.0'
#gem 'jwt' #error al estar junto a jwt_sessions
gem 'jwt_sessions', '~> 2.3'
gem 'rmagick', '~> 4.2.2'
gem 'mini_magick', '~> 4.11.0'
#gem 'knock'
gem "faraday"
gem "faraday_middleware"
gem 'will_paginate', '~> 3.3.0'

# Fix
gem 'net-smtp', require: false
gem 'net-pop', require: false
gem 'net-imap', require: false
#gem 'net-smtp-data', require: false
#gem 'net-smtp-ssl', require: false
#gem 'net-smtp-tls', require: false
#gem 'net-smtp-tlsdata', require: false
#gem 'net-smtp-tls-ssl', require: false




# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use ActiveStorage variant
# gem 'image_processing', '~> 1.2'
# gem 'mini_magick', '~> 4.8'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false



# group :development, :test do
#   # Call 'byebug' anywhere in the code to stop execution and get a debugger console
#   gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
#   gem 'pry', '~> 0.13.1'
# end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Added group to make test for the API
group :development, :test do
  # Deps added to make additional validations por rspec
  gem 'factory_bot_rails', '~> 4.0'
  gem 'shoulda', '~> 3.6.0'
  gem 'shoulda-matchers', '~> 3.1.3'
  gem 'rails-controller-testing', '~> 1.0.4'
  gem 'faker', '~> 1.9'
  gem 'database_cleaner', '~> 1.7'
  gem 'rspec-rails', '~> 3.5'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry', '~> 0.13.1'
end


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
